spring:
  application:
    name: underwriting

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:underwritingdb
      username: admin
      password: 123 